### ISSUE TITLE
Triangle and Fluid samples crash on launch

### ISSUE THREAD

**Issue by bvisness** [orca-app/orca#71]
On my M1 Macbook Air, the Triangle and Fluid samples crash on launch with the following error:

```
Error: oc_wgpu_canvas_on_device_error() in src/graphics/wgpu_renderer.c:395: Binding size for [Buffer "path buffer"] is zero.
 - While validating entries[0] as a Buffer.
Expected entry layout: { binding: 0, visibility: ShaderStage::Compute, buffer: { type: BufferBindingType::ReadOnlyStorage, hasDynamicOffset: 0, minBindingSize: 0 } }
 - While validating [BindGroupDescriptor] against [BindGroupLayout]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).
```

**Comment by martinfouilleul** [comment]
Fixed by [ffc3c8a1](https://github.com/orca-app/orca/commit/ffc3c8a11b914a6fb8eb3112b8c1425adc1439c8). See #72 for more details.

Here we were not entering the encode batch loop, but the overflow on the buffer size meant we were binding buffers with a size of 0, which is caught by wgpu validation.

Closing this issue, as further actions will be tracked in #72
